---
# Run checks first, then use gitlab pages feature to generate a badge that we
# can display in the pmaports project

image: alpine:latest
stages:
  - check
  - badge

.only-default: &only-default
  only:
    - master
    - merge_requests
    - tags

mr-settings:
  stage: check
  only:
    - merge_requests
  before_script:
    - apk -q add python3
  script:
    - wget -q "https://gitlab.com/postmarketOS/ci-common/-/raw/master/check_mr_settings.py"
    - python3 ./check_mr_settings.py

flake8:
  stage: check
  <<: *only-default
  image: "alpine:latest"
  before_script:
  - "apk -q add py3-pip"
  - "pip3 -q --disable-pip-version-check install flake8"
  script:
  - ".ci/flake8.sh"

upstream-compat-master:
  stage: check
  <<: *only-default
  allow_failure: true
  script:
  - ./test_upstream_compat_setup.sh "master"
  artifacts:
    when: always
    paths:
    - "*.check-passed"

upstream-compat-v20.05:
  stage: check
  <<: *only-default
  allow_failure: true
  script:
  - ./test_upstream_compat_setup.sh "v20.05"
  artifacts:
    when: always
    paths:
      - "*.check-passed"

pages:
  stage: badge
  <<: *only-default
  image: alpine:latest
  script:
  - ls -R .
  - .ci/generate_page.sh
  artifacts:
    paths:
    - public
